spring.application.name=routing-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5433/rotahub_routing
spring.datasource.username=rotahub
spring.datasource.password=rotahub

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
